### ISSUE TITLE
爬取微博话题的问题

### ISSUE THREAD

**Issue by hiredy** [CourierKyn/jkcrawler#2]
在爬取微博话题 的时候遇到问题，不知道怎么去修改爬取的话题，还有保存的格式

**Comment by CourierKyn** [comment]
见 [`jkcrawler/spiders/m_weibo.py`](https://github.com/CourierKyn/jkcrawler/blob/master/jkcrawler/spiders/m_weibo.py)，若要更换爬取的话题应修改 start_urls，然后保存的格式是指什么？

**Comment by hiredy** [comment]
你说的 我修改了，但是无法运行，可能是我转码的时候遇到的问题，因为这个保存的可能涉及到gif和jpg这几种方式，这个问题不知道出在了哪里！麻烦你帮助一下

**Comment by CourierKyn** [comment]
你把这个 repository fork 一下，我看看你的 fork 的代码
