### ISSUE TITLE
作为爬虫小白的问题

### ISSUE THREAD

**Issue by jameskitfu** [CourierKyn/jkcrawler#3]
首先呢，头像周杰伦好评 周杰伦10多年老粉了
然后，readme可不可以写的具体一些，不知道怎么把程序跑起来?

**Comment by CourierKyn** [comment]
我不太了解你的基础，但是能否说具体是哪里不懂呢？
另外，如果有python和scrapy基础的话，应该是没问题的。

**Comment by jameskitfu** [comment]
代码已经跑起来了，没有python基础，昨天晚上花时间看了下python文档，非常感谢及时回复，后续有问题再请教
